require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'iZero' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'iZeroTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'iZero-tvOS' do
  # Pods for iZero-tvOS

  target 'iZero-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
