const ADD_USER = 'ADD_USER';

const REVERT_APP = 'REVERT_APP';

const REVERT_AUTH = 'REVERT_AUTH';

const USER_DATA = 'USER_DATA';

const USER_TYPE = 'USER_TYPE';

const CREATE_JOB_ID = 'CREATE_JOB_ID';

const FIND_TALENT = 'FIND_TALENT';

const FIND_TALENTS = 'FIND_TALENTS';

const APPLICANTS = 'APPLICANTS';

const COMPLETED = 'COMPLETED';

const FAVOURITE = 'FAVOURITE';

const LIVE = 'LIVE';

const TALENTS = 'TALENTS';

const OVER_VIEW = 'OVER_VIEW';

const IN_PROGRESS = 'IN_PROGRESS';

const COMPLETED_FINANCE = 'COMPLETED_FINANCE';

const EXPENSES = 'EXPENSES';

const SAVED_QUOTES = 'SAVED_QUOTES';

const TOTAL_SPEND = 'TOTAL_SPEND';

const TOTAL_FEE = 'TOTAL_FEE';

const LIVE_JOBS = 'LIVE_JOBS';

const UP_COMINGS = 'UP_COMINGS';

const LOGIN_USER_STATUS = 'LOGIN_USER_STATUS';

const APPLIED = 'APPLIED';

const LIVE_BOOK = 'LIVE_BOOK';

const OFFERED_JOBS = 'OFFERED_JOBS';

const USER_ID_MESSAGES = 'USER_ID_MESSAGES';

const SEARCH_JOB = 'SEARCH_JOB';

const CALENDAR_LIST = 'CALENDAR_LIST';

const CALENDAR_LIST_AVAILBILITY = 'CALENDAR_LIST_AVAILBILITY';

const SHIFT_ID = 'SHIFT_ID';

const DEVICE_TOCKEN = 'DEVICE_TOCKEN';

const FCM_TOCKEN = 'FCM_TOCKEN';

const NOTIFICATION_TOTAL = 'NOTIFICATION_TOTAL';

const AVAILBILITY = 'AVAILBILITY';

const TALENT_SKILLS = 'TALENT_SKILLS';

const JOB_DETAILS = 'JOB_DETAILS';

const STAFF_EXPENSE_DETAILS = 'STAFF_EXPENSE_DETAILS';

const EMPLOYEER_EXPENSE_DETAILS = 'EMPLOYEER_EXPENSE_DETAILS';

const STAFF_DETAILS = 'STAFF_DETAILS';

const AVAILBILITY_CALENDAR_SHOW = 'AVAILBILITY_CALENDAR_SHOW';

const JOB_SECTORS = 'JOB_SECTORS';

const JOB_FEES = 'JOB_FEES';

const types = {
  ADD_USER,
  REVERT_APP,
  REVERT_AUTH,
  USER_DATA,
  USER_TYPE,
  CREATE_JOB_ID,
  FIND_TALENT,
  FIND_TALENTS,
  APPLICANTS,
  COMPLETED,
  FAVOURITE,
  LIVE,
  TALENTS,
  OVER_VIEW,
  IN_PROGRESS,
  COMPLETED_FINANCE,
  EXPENSES,
  SAVED_QUOTES,
  TOTAL_SPEND,
  TOTAL_FEE,
  LIVE_JOBS,
  UP_COMINGS,
  LOGIN_USER_STATUS,
  APPLIED,
  LIVE_BOOK,
  OFFERED_JOBS,
  USER_ID_MESSAGES,
  SEARCH_JOB,
  CALENDAR_LIST,
  CALENDAR_LIST_AVAILBILITY,
  SHIFT_ID,
  DEVICE_TOCKEN,
  FCM_TOCKEN,
  NOTIFICATION_TOTAL,
  AVAILBILITY,
  TALENT_SKILLS,
  JOB_DETAILS,
  STAFF_EXPENSE_DETAILS,
  EMPLOYEER_EXPENSE_DETAILS,
  STAFF_DETAILS,
  AVAILBILITY_CALENDAR_SHOW,
  JOB_SECTORS,
  JOB_FEES,
};

export default types;
